defaults:
  - _self_
  - dataset: movielens
  - teacher: ilora
  - student: sasrec
  - distill: dllm2rec
  - eval: default
  - train: default

# Basic experiment settings
seed: 42

run:
  dir: "result/result_${now:%Y%m%d_%H%M%S}"
job:
  chdir: true